---

name: Test Gaia Stateful Upgrade - v11
on:
  workflow_call:
    inputs:
      runs-on-os:
        required: true
        type: string
      gaia_version:
        required: true
        type: string
      upgrade_version:
        required: true
        type: string
jobs:
  test-upgrade:
    runs-on: ${{ inputs.runs-on-os }}
    environment: major-upgrade-stateful-workflow
    env:
      SSH_KEYS: ${{ vars.SSH_KEYS }}
      PROVIDER_SERVICE_1: ${{ vars.PROVIDER_SERVICE_1 }}
      CHAIN_BINARY: ${{ vars.CHAIN_BINARY }}
      HOME_1: ${{ vars.HOME_1 }}
      CHAIN_ID: ${{ vars.CHAIN_ID }}
      MONIKER_1: ${{ vars.MONIKER_1 }}
      MONIKER_2: ${{ vars.MONIKER_2 }}
      MNEMONIC_1: ${{ vars.MNEMONIC_1 }}
      MNEMONIC_2: ${{ vars.MNEMONIC_2 }}
      DENOM: ${{ vars.DENOM }}
      VAL_FUNDS: ${{ vars.VAL_FUNDS }}
      VAL_STAKE: ${{ vars.VAL_STAKE }}
      VAL_STAKE_STEP: ${{ vars.VAL_STAKE_STEP }}
      VOTING_PERIOD: ${{ vars.VOTING_PERIOD }}
      VAL1_RPC_PORT: 27001
      VAL1_API_PORT: 25001
      VAL1_GRPC_PORT: 26001
      VAL1_P2P_PORT: 28001
      VAL1_PPROF_PORT: 6061
      WALLET_1: ${{ vars.WALLET_1 }}
      WALLET_2: ${{ vars.WALLET_2 }}
      VALOPER_1: ${{ vars.VALOPER_1 }}
      CONSUMER_CHAIN_BINARY_URL: ${{ vars.CONSUMER_CHAIN_BINARY_URL }}
      CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY }}
      CONSUMER_CHAIN_BINARY_URL_2: ${{ vars.CONSUMER_CHAIN_BINARY_URL_2 }}
      CONSUMER_CHAIN_BINARY_2: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
      CONSUMER_DENOM: ${{ vars.CONSUMER_DENOM }}
      CONSUMER_HOME_1: /home/runner/.cona1
      CON1_API_PORT: 25101
      CON1_GRPC_PORT: 26101
      CON1_RPC_PORT: 27101
      CON1_P2P_PORT: 28101
      CON1_PPROF_PORT: 6163
      CONSUMER_SERVICE_1: cona1.service
      BASE_FEES: 5000
      HIGH_FEES: 10000
      GAS: auto
      GAS_ADJUSTMENT: 1.2
      DELEGATE_1: ${{ vars.DELEGATE_1 }}
      DELEGATE_1_AMOUNT: ${{ vars.DELEGATE_1_AMOUNT }}
    steps:
      # Get system info
      - run: ifconfig
      - run: lscpu
      - run: df -h
      - run: free -m
      - run: uname -a
      - run: lsb_release -a
      - run: echo "GitHub branch is ${{ github.ref }}"
      - run: whoami
      - run: pwd
      - name: mkdir ~/artifact
        run: mkdir ~/artifact
      - name: Update Apt
        run: |
          sudo apt update
          sudo apt dist-upgrade -y
      - name: Install openssh-server
        run: |
          sudo apt install -y openssh-server
          sudo mkdir /run/sshd
          sudo /usr/sbin/sshd
      - name: Setup SSH auth
        run: |
          mkdir -m 700 ~/.ssh
          echo "$SSH_KEYS" > ~/.ssh/authorized_keys
      - name: start-version
        run: echo ${{inputs.gaia_version}}
      - name: target-version
        run: echo ${{inputs.upgrade_version}}
      - name: target-commit
        if: ${{ inputs.upgrade_version == 'main' }}
        run: |
          BUILD_TAG=gaiad-linux-${{inputs.upgrade_version}}
          TARGET_COMMIT=$(curl -s -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/hyphacoop/cosmos-builds/releases/tags/$BUILD_TAG | jq -r '.name')
          echo $TARGET_COMMIT
      - name: Consumer chain binary URLs
        run: |
          echo "$CONSUMER_CHAIN_BINARY runs off $CONSUMER_CHAIN_BINARY_URL"
      - name: Update PATH
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH
          echo "$HOME/.hermes" >> $GITHUB_PATH
      - name: Bypass the grub-efi-amd64-signed package
        run: sudo apt-mark hold grub-efi-amd64-signed
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt -y install python-is-python3 python3-distutils screen curl jq wget python3-venv python3-pip
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Init Python venv
        run: python -m venv ~/env
      - name: Install dependencies
        run: |
          source ~/env/bin/activate
          python -m pip install --upgrade pip
          python -m pip install toml-cli
      - name: Print RPC port
        run: echo $VAL1_RPC_PORT
      - name: Test software upgrade for published releases
        if: ${{ inputs.upgrade_version != 'main' }}
        env:
          DOWNLOAD_URL: https://github.com/cosmos/gaia/releases/download/${{ inputs.upgrade_version }}/gaiad-${{ inputs.upgrade_version }}-linux-amd64
        run: |
          echo "$DOWNLOAD_URL"
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
      - name: Test software upgrade for main branch
        if: ${{ inputs.upgrade_version == 'main' }}
        env:
          DOWNLOAD_URL: https://github.com/hyphacoop/cosmos-builds/releases/download/gaiad-linux-main/gaiad-linux
        run: |
          echo "$DOWNLOAD_URL"
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
      - name: Start chain
        env:
          START_VERSION: ${{inputs.gaia_version}}
          ARCHIVE_URL: "https://files.polypore.xyz/archived-state/latest_v10.tar.gz"
        run: tests/major_stateful_upgrade/start_chain.sh
      - name: _blocks-1
        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 50 # 5 blocks
      - name: _txs-1
        run: tests/major_stateful_upgrade/test_tx.sh
      - name: Delegate to mainnet validator
        run:
          gaiad tx staking delegate $DELEGATE_1 $DELEGATE_1_AMOUNT$DENOM --from $MONIKER_2 --keyring-backend test --gas $GAS --gas-adjustment $GAS_ADJUSTMENT --fees $BASE_FEES$DENOM -y --chain-id $CHAIN_ID --home $HOME_1
      - name: _api-1
        run: tests/test_endpoints_api.sh localhost $VAL1_API_PORT
      - name: _rpc-1
        run: tests/test_endpoints_rpc.sh localhost $VAL1_RPC_PORT
      - name: Set up relayer
        run: tests/major_stateful_upgrade/setup_relayer.sh
      - name: Download consumer chain binaries
        run: |
          wget -nv $CONSUMER_CHAIN_BINARY_URL -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY
          chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY
          wget -nv $CONSUMER_CHAIN_BINARY_URL_2 -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY_2
          chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY_2
      - name: Set unbonding time via gov proposal
        run: tests/major_stateful_upgrade/set_unbonding-time.sh
      - name: Initialize consumer chain a with ICS v3.1.0
        env:
          CONSUMER_CHAIN_ID: consumera
          DOWNTIME_BLOCKS: 20
          CONSUMER_NEW: true
        run: tests/major_stateful_upgrade/init_consumer.sh
      - name: Launch consumer chain a
        env:
          CONSUMER_CHAIN_ID: consumera
        run: tests/major_stateful_upgrade/launch_consumer.sh
      - name: _consumera-blocks-1
        run: tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 10
      - name: Establish CCV channel for consumer a
        run: |
          client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumera").client_id')
          hermes create connection --a-chain consumera --a-client 07-tendermint-0 --b-client $client_id
          hermes create channel --a-chain consumera --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
          killall hermes
          echo "Wait for hermes to start..."
          sleep 180
      - name: _consumera-vsc-1
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _consumera-ibc-1
        env:
          CONSUMER_CHAIN_ID: consumera
        run: |
          client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumera").client_id')
          echo "Client ID: $client_id"
          connection_id=$(hermes --json query client connections --chain local-testnet --client $client_id | jq -r '. | select(.result).result[]')
          echo "Connection ID: $connection_id"
          channel_id=$(hermes --json query connection channels --chain local-testnet --connection $connection_id | jq -r '. | select(.result).result[] | select(.port_id=="transfer").channel_id')
          echo "Channel ID: $channel_id"
          tests/major_stateful_upgrade/test_consumer_ibc_transfer.sh $channel_id 2
      - name: _globalfee-2
        run: tests/v11_upgrade/test_bypass_msg.sh
      - name: _globalfee-3
        run: tests/v11_upgrade/test_max_gas.sh
      - name: _soft-opt-out-1
        run: tests/v11_upgrade/test_validator_jailed.sh $DELEGATE_1 true
      - name: _soft-opt-out-2
        run: tests/v11_upgrade/test_validator_jailed.sh cosmosvaloper10nzaaeh2kq28t3nqsh5m8kmyv90vx7ym5mpakx false
      - name: Initialize consumer chain b with ICS v2.0.0
        env:
          CONSUMER_CHAIN_ID: consumerb
          CONSUMER_HOME_1: /home/runner/.conb1
          CON1_API_PORT: 25201
          CON1_GRPC_PORT: 26201
          CON1_RPC_PORT: 27201
          CON1_P2P_PORT: 28201
          CON1_PPROF_PORT: 6165
          CONSUMER_SERVICE_1: conb1.service
          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
          DOWNTIME_BLOCKS: 1000
        run: tests/major_stateful_upgrade/init_consumer.sh
      - name: Launch consumer chain b
        env:
          CONSUMER_CHAIN_ID: consumerb
          CONSUMER_HOME_1: /home/runner/.conb1
          CONSUMER_SERVICE_1: conb1.service
        run: tests/major_stateful_upgrade/launch_consumer.sh
      - name: _consumerb-blocks-1
        run: tests/test_block_production.sh 127.0.0.1 27201 10
      - name: Establish CCV channel for consumer b
        run: |
          client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumerb").client_id')
          hermes create connection --a-chain consumerb --a-client 07-tendermint-0 --b-client $client_id
          hermes create channel --a-chain consumerb --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
          killall hermes
          echo "Wait for hermes to start..."
          sleep 180
      - name: _consumerb-vsc-1
        env:
          CON1_RPC_PORT: 27201
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _consumerb-ibc-1
        env:
          CONSUMER_CHAIN_ID: consumerb
          CONSUMER_HOME_1: /home/runner/.conb1
        run: |
          client_id=$(gaiad --home $HOME/.val1 q provider list-consumer-chains --output json | jq -r '.chains[] | select(.chain_id=="consumerb").client_id')
          echo "Client ID: $client_id"
          connection_id=$(hermes --json query client connections --chain local-testnet --client $client_id | jq -r '. | select(.result).result[]')
          echo "Connection ID: $connection_id"
          channel_id=$(hermes --json query connection channels --chain local-testnet --connection $connection_id | jq -r '. | select(.result).result[] | select(.port_id=="transfer").channel_id')
          echo "Channel ID: $channel_id"
          tests/major_stateful_upgrade/test_consumer_ibc_transfer.sh $channel_id 3
      - name: Stop services
        if: always()
        run: |
          killall screen
          sleep 20
      - name: Save config files
        if: always()
        run: |
          mkdir ~/artifact/configs
          rm ${{ vars.HOME_1 }}/config/genesis.json
          cp -rp ${{ vars.HOME_1 }}/config/ ~/artifact/configs/val1
          cp -rp ~/.hermes/ ~/artifact/configs/hermes/
          cp -rp ~/.cona1/config/ ~/artifact/configs/cona1
          cp -rp ~/.conb1/config/ ~/artifact/configs/conb1
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.runs-on-os }}_archived-upgrade-${{ inputs.gaia_version }}-${{ inputs.upgrade_version }}
          path: ~/artifact/
