---

name: Test Examples
on:
  workflow_dispatch:
  schedule:
    # At 9:00 on Mondays.
    - cron: '0 9 * * 1'
  push:
jobs:
  fresh-state-testnet:
    runs-on: ubuntu-22.04
    env:
      RPC_ENDPOINT: https://localhost:26657
    steps:
      - name: Bypass the grub-efi-amd64-signed package
        run: sudo apt-mark hold grub-efi-amd64-signed
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible toml
          ansible-galaxy install -r requirements.yml
      - name: Configure ansible.cfg
        run: echo "transport = local" >> ansible.cfg
      - name: Run playbook
        run: |
          ansible-playbook node.yml -i examples/inventory-local.yml --extra-vars "target=local reboot=false chain_home={{ node_user_home }}/.gaia node_user=runner enable_swap=false use_cosmovisor=false"
      - name: Check gaiad service
        run: systemctl status gaiad
      - name: Check blocks are being produced
        run: |
          tests/test_block_production.sh 127.0.0.1 26657 10
  rs-testnet:
    runs-on: ubuntu-22.04
    env:
      RPC_ENDPOINT: https://localhost:26657
    steps:
      - name: Bypass the grub-efi-amd64-signed package
        run: sudo apt-mark hold grub-efi-amd64-signed
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible toml
          ansible-galaxy install -r requirements.yml
      - name: Configure ansible.cfg
        run: echo "transport = local" >> ansible.cfg
      - name: Run playbook
        run: |
          ansible-playbook node.yml -i examples/inventory-local-rs-testnet.yml --extra-vars "target=local reboot=false node_user=runner enable_swap=false target_provider=127.0.0.1 target_consumer=127.0.0.1"
      - name: Check gaiad service
        run: systemctl status cv-provider
      - name: Check blocks are being produced
        run: |
          tests/test_block_production.sh 127.0.0.1 26650 10
