---

name: Test Gaia Fresh State Upgrade - v11
on:
  repository_dispatch:
    types: [new_main_build]
  workflow_dispatch:
  schedule:
    # Once a day at 13:15
    - cron: '15 13 * * 1'
jobs:
  set-version-matrix:
    runs-on: ubuntu-22.04
    steps:
      # Get system info
      - run: ifconfig
      - run: arp -a
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: uname -a
      - run: lsb_release -a
      - run: echo "GitHub branch is ${{ github.ref }}"
      - run: whoami
      - run: pwd
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      - name: Generate starting versions
        id: generate-start
        run: |
          start=$(tests/generate_version_matrix.py v10.0.0)
          echo $start
          echo "start_versions=$start" >> $GITHUB_OUTPUT
      - name: Generate upgrade versions
        id: generate-upgrade
        run: |
          upgrade=$(tests/generate_upgrade_matrix_fresh.py v10.0.0)
          echo $upgrade
          echo "upgrade_versions=$upgrade" >> $GITHUB_OUTPUT
    outputs:
      upgrade_versions: ${{ steps.generate-upgrade.outputs.upgrade_versions }}
  test-upgrade:
    runs-on: ubuntu-22.04
    needs: set-version-matrix
    strategy:
      matrix:
        ${{ fromJSON(needs.set-version-matrix.outputs.upgrade_versions) }}
      fail-fast: false
    environment: major-upgrade-fresh-workflow
    env:
      PROVIDER_SERVICE_1: ${{ vars.PROVIDER_SERVICE_1 }}
      CHAIN_BINARY: ${{ vars.CHAIN_BINARY }}
      HOME_1: ${{ vars.HOME_1 }}
      CHAIN_ID: ${{ vars.CHAIN_ID }}
      MONIKER_1: ${{ vars.MONIKER_1 }}
      MNEMONIC_1: ${{ vars.MNEMONIC_1 }}
      DENOM: ${{ vars.DENOM }}
      VAL_FUNDS: ${{ vars.VAL_FUNDS }}
      VAL_STAKE: ${{ vars.VAL_STAKE }}
      VAL_STAKE_STEP: ${{ vars.VAL_STAKE_STEP }}
      VOTING_PERIOD: ${{ vars.VOTING_PERIOD }}
      VAL1_RPC_PORT: 27001
      VAL1_API_PORT: 25001
      VAL1_GRPC_PORT: 26001
      VAL1_P2P_PORT: 28001
      VAL1_PPROF_PORT: 6061
      WALLET_1: ${{ vars.WALLET_1 }}
      WALLET_2: ${{ vars.WALLET_2 }}
      VALOPER_1: ${{ vars.VALOPER_1 }}
      CONSUMER_CHAIN_BINARY_URL: ${{ vars.CONSUMER_CHAIN_BINARY_URL }}
      CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY }}
      CONSUMER_DENOM: ${{ vars.CONSUMER_DENOM }}
      CONSUMER_CHAIN_BINARY_URL_2: ${{ vars.CONSUMER_CHAIN_BINARY_URL_2 }}
      CONSUMER_CHAIN_BINARY_2: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
      CONSUMER_HOME_1: /home/runner/.cona1
      CON1_API_PORT: 25101
      CON1_GRPC_PORT: 26101
      CON1_RPC_PORT: 27101
      CON1_P2P_PORT: 28101
      CON1_PPROF_PORT: 6163
      CONSUMER_SERVICE_1: cona1.service
      BASE_FEES: 1500
      HIGH_FEES: 10000
      GAS: auto
      GAS_ADJUSTMENT: 1.2
    steps:
      - name: start-version
        run: echo ${{matrix.gaia_version}}
      - name: target-version
        run: echo ${{matrix.upgrade_version}}
      - name: target-commit
        if: ${{ matrix.upgrade_version == 'main' }}
        run: |
          BUILD_TAG=gaiad-linux-${{matrix.upgrade_version}}
          TARGET_COMMIT=$(curl -s -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/hyphacoop/cosmos-builds/releases/tags/$BUILD_TAG | jq -r '.name')
          echo $TARGET_COMMIT
      - name: Consumer chain binary URL
        run: echo $CONSUMER_CHAIN_BINARY_URL
      - name: Update PATH
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH
          echo "$HOME/.hermes" >> $GITHUB_PATH
      - name: Bypass the grub-efi-amd64-signed package
        run: sudo apt-mark hold grub-efi-amd64-signed
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install toml-cli
      - name: Print RPC port
        run: echo $VAL1_RPC_PORT
      - name: Start chain
        env:
          START_VERSION: ${{matrix.gaia_version}}
        run: tests/major_fresh_upgrade/start_chain.sh
      - name: _blocks-1
        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 # 5 blocks
      - name: _txs-1
        run: tests/patch_upgrade/patch_test_tx.sh
      - name: _api-1
        run: tests/test_endpoints_api.sh localhost $VAL1_API_PORT
      - name: _rpc-1
        run: tests/test_endpoints_rpc.sh localhost $VAL1_RPC_PORT
      - name: Set minimum gas prices in globalfee module
        run: tests/v11_upgrade/set_minimum_gas_prices.sh
      - name: Set up relayer
        run: tests/patch_upgrade/patch_setup_relayer.sh
      - name: Download consumer chain binaries
        run: |
          wget $CONSUMER_CHAIN_BINARY_URL -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY
          chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY
          wget $CONSUMER_CHAIN_BINARY_URL_2 -O $HOME/go/bin/$CONSUMER_CHAIN_BINARY_2
          chmod +x $HOME/go/bin/$CONSUMER_CHAIN_BINARY_2
      - name: Initialize consumer chain a
        env:
          CONSUMER_CHAIN_ID: consumera
        run: tests/major_fresh_upgrade/init_consumer.sh
      - name: Launch consumer chain a
        env:
          CONSUMER_CHAIN_ID: consumera
        run: tests/major_fresh_upgrade/launch_consumer.sh
      - name: _consumera-blocks-1
        run: tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 5
      - name: Establish CCV channel for consumer a
        run: |
          hermes create connection --a-chain consumera --a-client 07-tendermint-0 --b-client 07-tendermint-0
          hermes create channel --a-chain consumera --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
          sudo systemctl restart hermes
          sleep 10
      - name: _consumera-vsc-1
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _consumera-ibc-1
        env:
          CONSUMER_CHAIN_ID: consumera
        run: tests/major_fresh_upgrade/test_consumer_ibc_transfer.sh channel-1 2
      - name: Initialize consumer chain b
        env:
          CONSUMER_CHAIN_ID: consumerb
          CONSUMER_HOME_1: /home/runner/.conb1
          CON1_API_PORT: 25201
          CON1_GRPC_PORT: 26201
          CON1_RPC_PORT: 27201
          CON1_P2P_PORT: 28201
          CON1_PPROF_PORT: 6165
          CONSUMER_SERVICE_1: conb1.service
          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
        run: tests/major_fresh_upgrade/init_consumer.sh
      - name: Launch consumer chain b
        env:
          CONSUMER_CHAIN_ID: consumerb
          CONSUMER_HOME_1: /home/runner/.conb1
          CONSUMER_SERVICE_1: conb1.service
        run: tests/major_fresh_upgrade/launch_consumer.sh
      - name: _consumerb-blocks
        run: tests/test_block_production.sh 127.0.0.1 27201 5
      - name: Establish CCV channel for consumer b
        run: |
          hermes create connection --a-chain consumerb --a-client 07-tendermint-0 --b-client 07-tendermint-1
          hermes create channel --a-chain consumerb --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
          sudo systemctl restart hermes
          sleep 10
      - name: _consumerb-vsc
        env:
          CON1_RPC_PORT: 27201
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _consumerb-ibc
        env:
          CONSUMER_CHAIN_ID: consumerb
          CONSUMER_HOME_1: /home/runner/.conb1
          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
        run: tests/major_fresh_upgrade/test_consumer_ibc_transfer.sh channel-3 3
      - name: Stop consumerb chain
        env:
          CONSUMER_CHAIN_ID: consumerb
        run: tests/major_fresh_upgrade/remove_consumer.sh
      - name: _consumerb-remove
        run: tests/patch_upgrade/patch_test_consumer_removed.sh
      - name: _consumera-blocks-2
        run: tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 5
      - name: _consumera-vsc-2
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _blocks-2
        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT
      - name: Test software upgrade for published releases
        if: ${{ matrix.upgrade_version != 'main' }}
        env:
          DOWNLOAD_URL: https://github.com/cosmos/gaia/releases/download/${{ matrix.upgrade_version }}/gaiad-${{ matrix.upgrade_version }}-linux-amd64
        run: |
          echo $DOWNLOAD_URL
          tests/major_fresh_upgrade/software_upgrade.sh 127.0.0.1 $VAL1_RPC_PORT v11
      - name: Test software upgrade for main branch
        if: ${{ matrix.upgrade_version == 'main' }}
        env:
          DOWNLOAD_URL: https://github.com/hyphacoop/cosmos-builds/releases/download/gaiad-linux-main/gaiad-linux
        run: |
          tests/major_fresh_upgrade/software_upgrade.sh 127.0.0.1 $VAL1_RPC_PORT v11
      - name: _consumera-blocks-3
        run: tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 5
      - name: _consumera-vsc-3
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _blocks-3
        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 # blocks to wait for
      - name: _txs-2
        env:
          BASE_FEES: 2000
        run: tests/patch_upgrade/patch_test_tx.sh
      - name: _api-2
        run: tests/test_endpoints_api.sh localhost $VAL1_API_PORT
      - name: _rpc-2
        run: tests/test_endpoints_rpc.sh localhost $VAL1_RPC_PORT
      - name: Initialize consumer chain c
        env:
          CONSUMER_CHAIN_ID: consumerc
          CONSUMER_HOME_1: /home/runner/.conc1
          CON1_API_PORT: 25301
          CON1_GRPC_PORT: 26301
          CON1_RPC_PORT: 27301
          CON1_P2P_PORT: 28301
          CON1_PPROF_PORT: 6167
          CONSUMER_SERVICE_1: conc1.service
        run: tests/major_fresh_upgrade/init_consumer.sh
      - name: Launch consumer chain c
        env:
          CONSUMER_CHAIN_ID: consumerc
          CONSUMER_HOME_1: /home/runner/.conc1
          CONSUMER_HOME_2: /home/runner/.conc2
          CONSUMER_SERVICE_1: conc1.service
        run: |
          tests/major_fresh_upgrade/launch_consumer.sh
          sleep 10
          journalctl -u $CONSUMER_SERVICE_1
      - name: _consumerc-blocks
        run: tests/test_block_production.sh 127.0.0.1 27301 5
      - name: Establish CCV channel for consumer c
        run: |
          hermes create connection --a-chain consumerc --a-client 07-tendermint-0 --b-client 07-tendermint-2
          hermes create channel --a-chain consumerc --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
          sudo systemctl restart hermes
          sleep 10
      - name: _consumerc-vsc
        env:
          CON1_RPC_PORT: 27301
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _consumerc-ibc
        env:
          CONSUMER_CHAIN_ID: consumerc
          CONSUMER_HOME_1: /home/runner/.conc1
        run: tests/major_fresh_upgrade/test_consumer_ibc_transfer.sh channel-5 4
      - name: Stop consumerc chain
        env:
          CONSUMER_CHAIN_ID: consumerc
        run: tests/major_fresh_upgrade/remove_consumer.sh
      - name: _consumerc-remove
        run: tests/patch_upgrade/patch_test_consumer_removed.sh
      - name: Initialize consumer chain f
        env:
          CONSUMER_CHAIN_ID: consumerf
          CONSUMER_HOME_1: /home/runner/.conf1
          CON1_API_PORT: 25401
          CON1_GRPC_PORT: 26401
          CON1_RPC_PORT: 27401
          CON1_P2P_PORT: 28401
          CON1_PPROF_PORT: 6169
          CONSUMER_SERVICE_1: conf1.service
          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
        run: tests/major_fresh_upgrade/init_consumer.sh
      - name: Launch consumer chain f
        env:
          CONSUMER_CHAIN_ID: consumerf
          CONSUMER_HOME_1: /home/runner/.conf1
          CONSUMER_SERVICE_1: conf1.service
        run: tests/major_fresh_upgrade/launch_consumer.sh
      - name: _consumerf-blocks
        run: tests/test_block_production.sh 127.0.0.1 27401 5
      - name: Establish CCV channel for consumer f
        run: |
          hermes create connection --a-chain consumerf --a-client 07-tendermint-0 --b-client 07-tendermint-3
          hermes create channel --a-chain consumerf --a-port consumer --b-port provider --order ordered --a-connection connection-0 --channel-version 1
          sudo systemctl restart hermes
          sleep 10
      - name: _consumerf-vsc
        env:
          CON1_RPC_PORT: 27401
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _consumerf-ibc
        env:
          CONSUMER_CHAIN_ID: consumerf
          CONSUMER_HOME_1: /home/runner/.conf1
          CONSUMER_CHAIN_BINARY: ${{ vars.CONSUMER_CHAIN_BINARY_2 }}
        run: tests/major_fresh_upgrade/test_consumer_ibc_transfer.sh channel-7 5
      - name: Stop consumerf chain
        env:
          CONSUMER_CHAIN_ID: consumerf
        run: tests/major_fresh_upgrade/remove_consumer.sh
      - name: _consumerf-remove
        run: tests/patch_upgrade/patch_test_consumer_removed.sh
      - name: _consumera-blocks-4
        run: tests/test_block_production.sh 127.0.0.1 $CON1_RPC_PORT 5
      - name: _consumera-vsc-4
        run: tests/patch_upgrade/patch_test_ccv.sh
      - name: _blocks-4
        run: tests/test_block_production.sh 127.0.0.1 $VAL1_RPC_PORT 5 # 5 blocks
      - name: _txs-3
        run: tests/patch_upgrade/patch_test_tx.sh
      - name: _api-3
        run: tests/test_endpoints_api.sh localhost $VAL1_API_PORT
      - name: _rpc-3
        run: tests/test_endpoints_rpc.sh localhost $VAL1_RPC_PORT
      - name: _globalfee-1
        run: tests/v11_upgrade/test_globalfee_params.sh
      - name: _globalfee-2
        run: tests/v11_upgrade/test_bypass_msg.sh
      - name: _globalfee-3
        run: tests/v11_upgrade/test_max_gas.sh
