---

name: Test Gaia Fresh State Upgrade - v11
on:
    workflow_dispatch:
    schedule:
    # Once a day at 13:15
    - cron: '15 13 * * 1'
    push:
        paths-ignore:
        - 'docs/**'
        - 'examples/**'
        - 'logs/**'
        - '!examples/inventory-local.yml'
        - 'README.md'
jobs:
    generate-matrices:
        runs-on: ubuntu-22.04
        steps:
          # Get system info
          - run: ifconfig
          - run: arp -a
          - run: sudo dmidecode
          - run: df -h
          - run: free -m
          - run: uname -a
          - run: lsb_release -a
          - run: echo "GitHub branch is ${{ github.ref }}"
          - run: whoami
          - run: pwd
    
          - name: Check out repository code
            uses: actions/checkout@v3
    
          - name: Set up Python
            uses: actions/setup-python@v3
            with:
              python-version: '3.10'
    
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install requests
    
          - name: Generate starting versions
            id: generate-start
            run: |
              start=$(tests/generate_version_matrix.py v10.0.0)
              echo $start
              echo "start_versions=$start" >> $GITHUB_OUTPUT
          - name: Generate upgrade versions
            id: generate-upgrade
            run: |
              upgrade=$(tests/generate_upgrade_matrix.py v10.0.0)
              echo $upgrade
              echo "upgrade_versions=$upgrade" >> $GITHUB_OUTPUT
        outputs:
          start_versions: ${{ steps.generate-start.outputs.start_versions }}
          upgrade_versions: ${{ steps.generate-upgrade.outputs.upgrade_versions }}
    
    test-upgrade:
        runs-on: ubuntu-22.04
        needs: generate-matrices
        strategy:
          fail-fast: false
          matrix:
            ${{ fromJSON(needs.generate-matrices.outputs.upgrade_versions) }}
        steps:
          - name: Bypass the grub-efi-amd64-signed package
            run: sudo apt-mark hold grub-efi-amd64-signed
          - run: echo "Test upgrading ${{matrix.gaia_version}} to ${{matrix.upgrade_version}}"
          - name: Check out repository code
            uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v3
            with:
              python-version: '3.10'
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install ansible toml
          - name: Configure ansible.cfg
            run: echo "transport = local" >> ansible.cfg
          - name: Install ansible-galaxy requirements
            run: ansible-galaxy install --timeout 120 --verbose -r requirements.yml
          - name: Update PATH with cosmovisor binary
            run: echo "$HOME/.gaia/cosmovisor/current/bin" >> $GITHUB_PATH
          - name: Run playbook
            run: ansible-playbook node.yml -i examples/inventory-local.yml --extra-vars "target=local reboot=false chain_version=${{ matrix.gaia_version }} chain_home={{ node_user_home }}/.gaia chain_gov_testing=true api_enabled=true node_user=runner go_version=1.20.4 chain_binary_source=release chain_binary_release=https://github.com/cosmos/gaia/releases/download/${{ matrix.gaia_version }}/gaiad-${{ matrix.gaia_version }}-linux-amd64"
          - name: Check cosmovisor service
            run: systemctl status cosmovisor
          - name: Check blocks are being produced
            run: tests/test_block_production.sh 127.0.0.1 26657
          - name: Set minimum gas prices in globalfee module
            run: tests/v11_upgrade/set_minimum_gas_prices.sh
          - name: Test software upgrade for published releases
            if: ${{ matrix.upgrade_version != 'main' }}
            env:
              DOWNLOAD_URL: https://github.com/cosmos/gaia/releases/download/${{ matrix.upgrade_version }}/gaiad-${{ matrix.upgrade_version }}-linux-amd64
            run: |
              echo $DOWNLOAD_URL
              tests/test_software_upgrade_fresh.sh 127.0.0.1 26657 v11
          - name: Test software upgrade for main branch
            if: ${{ matrix.upgrade_version == 'main' }}
            env:
              DOWNLOAD_URL: https://github.com/hyphacoop/cosmos-builds/releases/download/gaiad-linux-main/gaiad-linux
            run: |
              tests/test_software_upgrade_fresh.sh 127.0.0.1 26657 v11
          - name: Happy path - transaction testing
            run: tests/test_tx_fresh.sh
          - name: Happy path - API endpoints testing
            run: tests/test_endpoints_api.sh localhost 1317
          - name: Happy path - RPC endpoints testing
            run: tests/test_endpoints_rpc.sh localhost 26657
          - name: Happy path - globalfee params
            run: tests/v11_upgrade/test_globalfee_params.sh
          - name: Happy path - test bypass messages
            run: tests/v11_upgrade/test_bypass_msg.sh
