---

name: Join Replicated Security Testnet
on:
  workflow_dispatch:
  schedule:
    # At 14:30 on M/W/F.
    - cron: '30 14 * * 1,3,5'
  push:
jobs:
  test-provider:
    runs-on: ubuntu-22.04
    steps:
      - name: Bypass the grub-efi-amd64-signed package
        run: sudo apt-mark hold grub-efi-amd64-signed
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible toml
      - name: Configure ansible.cfg
        run: echo "transport = local" >> ansible.cfg
      - name: Run playbook
        run: |
          chain_version=$(curl -s https://rpc.provider-sentry-02.rs-testnet.polypore.xyz/abci_info? | jq -r '.result.response.version')
          ansible-playbook node.yml -i examples/inventory-rs-testnet-provider.yml --extra-vars "target=local reboot=false chain_version=$chain_version chain_home={{ node_user_home }}/.gaia node_user=runner enable_swap=false use_cosmovisor=false chain_binary_release=https://github.com/cosmos/gaia/releases/download/$chain_version/gaiad-$chain_version-linux-amd64"
      - name: Check gaia service
        run: systemctl status gaiad
      - name: Check blocks are being produced
        run: |
          height=$(curl -s http://rpc.provider-sentry-02.rs-testnet.polypore.xyz:26657/block | jq -r '.result.block.header.height')
          echo "Waiting for block $[ $height + 10 ]..."
          tests/test_block_production.sh 127.0.0.1 26657 10
